#----------------------------------------------------------------------------------------------------------------------
# HELPFUL REFERENCES:
#  - https://docs.aws.amazon.com/en_pv/codedeploy/latest/userguide/troubleshooting-deployments.html#troubleshooting-skipped-lifecycle-events
#  - https://docs.aws.amazon.com/en_pv/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#appspec-hooks-server
#
#  Location of CodeDeploy agent log on EC2 Linux: /var/log/aws/codedeploy-agent/codedeploy-agent.log
#  Location of deployment logs (including lifecycle scripts output): /opt/codedeploy-agent/deployment-root/deployment-logs
#----------------------------------------------------------------------------------------------------------------------
version: 0.0
os: linux
files:
  - source: target/simple-spring-boot-app.jar
    destination: /var/app
#  - source: Config/config.txt
#    destination: /webapps/Config

#  For all of the files in the /var/app folder ending in .jar
#  (for example, simple-spring-boot-app.jar), owner = root, group = root,
#  and mode = 754 (-rwxr-xr--).
permissions:
  - object: /var/app
    pattern: "*.jar"
    owner: root
    group: root
    mode: 754
    type:
      - file

hooks:
  BeforeInstall:
    - location: codedeploy/delete-last-deployment.sh
      timeout: 15
      runas: root
  AfterInstall:
    - location: codedeploy/after-install.sh
      timeout: 10
      runas: root
  ApplicationStop:
    - location: codedeploy/stop-app.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: codedeploy/start-app.sh
#    - location: scripts/start_server.sh
#    - location: scripts/create_test_db.sh
      timeout: 60
      runas: root
